//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliHackV4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoliHackV4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;C:\Users\Alex-PC\Documents\Visual Studio 2015\Projects\PoliHackV4\PoliHackV4\DatabaseApp.mdf&quot;;Integrated Security=True.
        /// </summary>
        internal static string ConnectionStringLogin {
            get {
                return ResourceManager.GetString("ConnectionStringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Data Source = (LocalDB)\\MSSQLLocalDB;AttachDbFilename=&quot; + &quot;C:\\Users\\Horatiu\\Desktop\\PoliHack5\\PoliHackV4\\DatabaseApp.mdf;&quot; + &quot;Integrated Security = True&quot;.
        /// </summary>
        internal static string ConnectionStringLoginHoratiu {
            get {
                return ResourceManager.GetString("ConnectionStringLoginHoratiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Data Source = (LocalDB)\\MSSQLLocalDB;AttachDbFilename=&quot; + &quot;D:\\C#\\PoliHack6\\PoliHackV4\\DatabaseApp.mdf;&quot; + &quot;Integrated Security = True&quot;.
        /// </summary>
        internal static string ConnectionStringLoginTeo {
            get {
                return ResourceManager.GetString("ConnectionStringLoginTeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__1_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__1_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__2_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__2_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__3_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__3_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__4_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__4_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__5_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__5_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__6_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__6_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__7_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__7_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__8_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__8_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icons_Land_Medical_People_Doctor_Male__9_ {
            get {
                object obj = ResourceManager.GetObject("Icons_Land_Medical_People_Doctor_Male__9_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBA
        ///ARAD
        ///ARGES
        ///BACAU
        ///BIHOR
        ///BISTRITA-NASAUD
        ///BOTOSANI
        ///BRAILA
        ///BRASOV
        ///BUCURESTI
        ///BUZAU
        ///CALARASI
        ///CARAS-SEVERIN
        ///CLUJ
        ///CONSTANTA
        ///COVASNA
        ///DIMBOVITA
        ///DOLJ
        ///GALATI
        ///GIURGIU
        ///GORJ
        ///HARGHITA
        ///HUNEDOARA
        ///IALOMITA
        ///IASI
        ///ILFOV
        ///MARAMURES
        ///MEHEDINTI
        ///MURES
        ///NEAMT
        ///OLT
        ///PRAHOVA
        ///SALAJ
        ///SATU MARE
        ///SIBIU
        ///SUCEAVA
        ///TELEORMAN
        ///TIMIS
        ///TULCEA
        ///VASLUI
        ///VILCEA
        ///VRANCEA
        ///.
        /// </summary>
        internal static string judete {
            get {
                return ResourceManager.GetString("judete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Alex-PC\Documents\Visual Studio 2015\Projects\PoliHackV4\judete.txt.
        /// </summary>
        internal static string JudeteString {
            get {
                return ResourceManager.GetString("JudeteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap romania {
            get {
                object obj = ResourceManager.GetObject("romania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f6\fnil\fprq2\fcharset0 Arial;}{\f7\fswiss\fprq0\fcharset128 Arial;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\green255\blue255;\red0\green255\blue0;\red255\green [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uk {
            get {
                object obj = ResourceManager.GetObject("uk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
